// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import BrandSuggestController from "./brand_suggest_controller"
import FlavorSelectController from "./flavor_select_controller"
import BrandController from "./brand_controller"
import FlavorController from "./flavor_controller"
import ModalController from "./modal_controller"
import FlashController from "./flash_controller"

application.register("hello", HelloController)
application.register("brand-suggest", BrandSuggestController)
application.register("flavor-select", FlavorSelectController)
application.register("brand", BrandController)
application.register("flavor", FlavorController)
application.register("modal", ModalController)
application.register("flash", FlashController)